name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm Dependencies
      run: npm install
      
    - name: Manualy change the config.js file
      run: echo "export const settings = { host:'http:localhost:3030' };" > src/api/config.js
       
    - name: Run Back-End
      run: npm run server &
      
    - name: Run Front-End
      run: npm run start &

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Tests
      run: npm run test
      
